ebr-randy-develop/ebr_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from frontend.sitemaps import StaticViewSitemap, ReviewCategorySitemap, ReviewBrandSitemap, ReviewSitemap, PagesSitemap

sitemaps = {
    'static': StaticViewSitemap, 'review_category': ReviewCategorySitemap,
    'review_brand': ReviewBrandSitemap, 'review': ReviewSitemap,
    'pages': PagesSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customadmin/', include("core.urls")),
    path('', include("frontend.urls")),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps, 'template_name': 'frontend/custom_sitemap.html'}),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),


    #change


    path('customlogin/',include('customloginapp.urls'))


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'frontend.views.error_404_view'

ebr-randy-develop/frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"


urlpatterns = [
	# Extra API for EBR.
	path('dashboard-integration/shops-nearby/', views.shops_nearby, name='shops_nearby'),
	path('dashboard-integration/shops-osm/', views.shops_osm, name='shops_osm'),
	path('ar/brands/', views.brand_json, name='brand_json'),
	path('wp-json/dashboard/brands/', views.dashboard_brands, name='dashboard_brands'),
	path('visitor_history/', views.visitor_history, name='visitor_history'),

	path('', views.index, name='dashboard'),
	path('category/', views.category, name='category'),
	path('category/<str:cat_slug>/', views.category_detail, name='category_detail'),
	path('search_filter/', views.search_filter, name='search-filter'),
	path('price-range/', views.price_range_filter, name='price-range-filter'),
	path('more-filter/', views.more_filter, name='more-filter'),
 
	path('display-comments/', views.display_comments, name='display-comments'),
	path('display-sub-comments/', views.display_sub_comments, name='display-sub-comments'),
 
	path('search/', views.category_filter, name='search-reviews'),

	path('category-count-ajax/', views.category_count_ajax, name='category-count-ajax' ),

	path('brand/', views.brand, name='brand'),
	path('brand/<str:brand_slug>/', views.brand_details, name='brand_details'),
	path('review_seo', views.review_seo, name='review_seo'),
 
 	path('send-message/', views.send_message, name='send_message'),
 	# path('send-message/<str:page_slug>/', views.send_message, name='send_message'),

	path('<str:brand_slug>/<str:slug>/', views.review_detail, name='review-detail'),
	path('add-new-comment/', views.add_new_comment, name='add-new-comment'),
	# path('add-new-comment/<str:brand_slug>/<str:slug>/', views.add_new_comment, name='add-new-comment'),
	path('compare/', views.compare, name='compare'),
 
 	# path('contact/', views.contact_us, name='contact'),
	# path('upvote-to-comment/', views.upvote_to_comment, name='upvote-to-comment'),

	path('highlights/update_vote', views.highlights_update_vote, name='highlights_update_vote'),
	path('highlights/get', views.get_review_highlights, name='get_review_highlights'),

	# path('<str:brand>/<str:slug>/', views.review_page, name='review'),
	path('<str:page_slug>/', views.page_view, name='page_view'),
	path('add_datas/<int:pk>', views.add_fields, name='add_datas'),
]

ebr-randy-develop/core/models/contact.py
from django.db import models


class ContactUs(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    message = models.TextField()
    is_spam = models.BooleanField(default=False)
    
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.name)
    
    class Meta:
        db_table = "contact_us"
        verbose_name = "contact_us"
        verbose_name_plural = "contact_us"

ebr-randy-develop/core/models/users.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext as _


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):

        """create a new user and super user in model"""

        account = self.model(
            email=self.normalize_email(email),
            # username=kwargs.get("username")
        )
        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, email, password, **kwargs):
        account = self.create_user(email, password, **kwargs)

        account.is_superuser = True
        account.is_staff = True
        account.is_admin = True
        account.save()

        return account


class User(AbstractBaseUser, PermissionsMixin):
    """
    User model
    """

    LOGIN_TYPE = (
        ("EMAIL", _("EMAIL")),
        ("GOOGLE", _("GOOGLE")),
        ("Facebook", _("Facebook")),
        ("Twitter", _("Twitter")),
    )
    email = models.EmailField(null=True, blank=True, unique=True)
    full_name = models.CharField(max_length=80, blank=True)
    profile_image = models.ImageField(
        upload_to="profile_image",
        null=True,
        blank=True,
        verbose_name=_("Profile Image"),
    )
    password = models.CharField(max_length=255, null=True)
    login_type = models.CharField(max_length=50, choices=LOGIN_TYPE, default="EMAIL")
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return str(self.email)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        ordering = ["-created_at"]
        db_table = "users"


class ReviewCSV1(models.Model):
    URL = models.TextField(null=True, blank=True)
    Year = models.TextField(null=True, blank=True)
    Brand = models.TextField(null=True, blank=True)
    Model = models.TextField(null=True, blank=True)
    Trim = models.TextField(null=True, blank=True)
    MSRP = models.TextField(null=True, blank=True)
    Class = models.TextField(null=True, blank=True)
    Frame_Type = models.TextField(null=True, blank=True)
    Frame = models.TextField(null=True, blank=True)
    Weight = models.TextField(null=True, blank=True)
    Load_Capacity = models.TextField(null=True, blank=True)
    Suspension = models.TextField(null=True, blank=True)
    Fork = models.TextField(null=True, blank=True)
    Rear_Shock = models.TextField(null=True, blank=True)
    Wheel_Size = models.TextField(null=True, blank=True)
    Front_Wheel = models.TextField(null=True, blank=True)
    Rear_Wheel = models.TextField(null=True, blank=True)
    Front_Hub = models.TextField(null=True, blank=True)
    Rear_Hub = models.TextField(null=True, blank=True)
    Tires = models.TextField(null=True, blank=True)
    Gears = models.TextField(null=True, blank=True)
    Shift_Levers = models.TextField(null=True, blank=True)
    Front_Derailleur = models.TextField(null=True, blank=True)
    Crankset = models.TextField(null=True, blank=True)
    Rear_Derailleur = models.TextField(null=True, blank=True)
    Electronic_Shifting = models.TextField(null=True, blank=True)
    Internally_Geared_Hub = models.TextField(null=True, blank=True)
    Continually_Variable_Transmission = models.TextField(null=True, blank=True)
    Cassette = models.TextField(null=True, blank=True)
    Chainring = models.TextField(null=True, blank=True)
    Belt_Drive = models.TextField(null=True, blank=True)
    Headset = models.TextField(null=True, blank=True)
    Stem = models.TextField(null=True, blank=True)
    Handlebar = models.TextField(null=True, blank=True)
    Grips = models.TextField(null=True, blank=True)
    Seatpost = models.TextField(null=True, blank=True)
    Seatpost_Diameter = models.TextField(null=True, blank=True)
    Saddle = models.TextField(null=True, blank=True)
    Pedals = models.TextField(null=True, blank=True)
    Brake_Type = models.TextField(null=True, blank=True)
    Front_Brake = models.TextField(null=True, blank=True)
    Rear_Brake = models.TextField(null=True, blank=True)
    Motor_Type = models.TextField(null=True, blank=True)
    Motor = models.TextField(null=True, blank=True)
    Additional_Motors = models.TextField(null=True, blank=True)
    Motor_Nominal_Output = models.TextField(null=True, blank=True)
    Display = models.TextField(null=True, blank=True)
    Smart_Bike = models.TextField(null=True, blank=True)
    Theft_GPS = models.TextField(null=True, blank=True)
    Additional_Battery = models.TextField(null=True, blank=True)
    Battery_Watt_Hrs = models.TextField(null=True, blank=True)
    Battery = models.TextField(null=True, blank=True)
    Charger = models.TextField(null=True, blank=True)
    Lights = models.TextField(null=True, blank=True)
    Fenders = models.TextField(null=True, blank=True)
    Front_Rack = models.TextField(null=True, blank=True)
    Rear_Rack = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "review_csv_1"


class ReviewCSV2(models.Model):
    URL = models.TextField( null=True, blank=True)
    Cruiser = models.TextField( null=True, blank=True)
    City = models.TextField( null=True, blank=True)
    Commuting = models.TextField( null=True, blank=True)
    Folding = models.TextField( null=True, blank=True)
    Fat = models.TextField( null=True, blank=True)
    Hunting = models.TextField( null=True, blank=True)
    All_Other_Fat = models.TextField( null=True, blank=True)
    Mountain = models.TextField( null=True, blank=True)
    Cross_Country = models.TextField( null=True, blank=True)
    Trail = models.TextField( null=True, blank=True)
    All_Mountain_Enduro = models.TextField( null=True, blank=True)
    Freeride_Downhill = models.TextField( null=True, blank=True)
    All_Other_Mountain = models.TextField( null=True, blank=True)
    Cargo = models.TextField( null=True, blank=True)
    Utility = models.TextField( null=True, blank=True)
    Box_Bike = models.TextField( null=True, blank=True)
    All_Other_Cargo = models.TextField( null=True, blank=True)
    Road = models.TextField( null=True, blank=True)
    Drop_Bars = models.TextField( null=True, blank=True)
    Gravel = models.TextField( null=True, blank=True)
    All_Other_Road = models.TextField( null=True, blank=True)
    Trike = models.TextField( null=True, blank=True)
    Delta = models.TextField( null=True, blank=True)
    Tadpole = models.TextField( null=True, blank=True)
    All_Other_Trike = models.TextField( null=True, blank=True)
    Recumbent = models.TextField( null=True, blank=True)
    Minibike = models.TextField( null=True, blank=True)
    Kids = models.TextField( null=True, blank=True)
    Other = models.TextField( null=True, blank=True)

    class Meta:
        verbose_name = "review_csv_2"


class ReviewCSV3(models.Model):
    URL = models.TextField( null=True, blank=True)
    Suggested_Use = models.TextField( null=True, blank=True)
    Warranty = models.TextField( null=True, blank=True)
    Availability = models.TextField( null=True, blank=True)
    Battery_Weight = models.TextField( null=True, blank=True)
    Motor_Weight = models.TextField( null=True, blank=True)
    Frame_Sizes = models.TextField( null=True, blank=True)
    Geometry_Measurements = models.TextField( null=True, blank=True)
    Frame_Colors = models.TextField( null=True, blank=True)
    Attachment_Points = models.TextField( null=True, blank=True)
    Brake_Details = models.TextField( null=True, blank=True)
    Seatpost_Length = models.TextField( null=True, blank=True)
    Spokes = models.TextField( null=True, blank=True)
    Tire_Details = models.TextField( null=True, blank=True)
    Tube_Details = models.TextField( null=True, blank=True)
    Accessories = models.TextField( null=True, blank=True)
    Other = models.TextField( null=True, blank=True)
    Motor_Output_Peak = models.TextField( null=True, blank=True)
    Motor_Torque = models.TextField( null=True, blank=True)
    Battery_Chemistry = models.TextField( null=True, blank=True)
    Charge_Time = models.TextField( null=True, blank=True)
    Estimated_Min_Range = models.TextField( null=True, blank=True)
    Estimated_Max_Range = models.TextField( null=True, blank=True)
    Display_Readouts = models.TextField( null=True, blank=True)
    Display_Accessories = models.TextField( null=True, blank=True)
    Drive_Mode = models.TextField( null=True, blank=True)
    Drive_Mode_Details = models.TextField( null=True, blank=True)
    Top_Speed = models.TextField( null=True, blank=True)

    class Meta:
        verbose_name = "review_csv_3"

ebr-randy-develop/core/models/visitor_history.py
from django.db import models


class VisitorHistory(models.Model):
    ip = models.CharField(max_length=80)
    type = models.CharField(max_length=100)
    type_name = models.CharField(max_length=150)
    type_url = models.CharField(max_length=255)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "visitor_history"
        verbose_name = "Visitor History"
        verbose_name_plural = "Visitor Histories"
        indexes = [
            models.Index(fields=['id']),
            models.Index(fields=['ip', 'type']),
        ]

ebr-randy-develop/core/forms/comments.py
# -*- coding: utf-8 -*-
from django import forms
from core.models import Comments, Review, ReviewBrand, ReviewCategory, Pages
from core.utils import send_reply_mail


# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------
class CommentsCreationForm(forms.ModelForm):
    """Custom Comments"""
    class Meta:
        model = Comments
        fields = ['name', 'email', 'ip', 'description', 'is_approved']
        # exclude = ('create_at', 'update_at')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    # def clean(self):
    #     cleaned_data = super(CommentsCreationForm, self).clean()
        # parent_id = cleaned_data.get('parent_id')
        # if parent_id is None:
        #     raise forms.ValidationError("Please parent comment not found.")

    def save(self, commit=True):
        instance = super().save(commit=False)
        domain = 'http://54.213.76.238'
        if commit:
            instance.save()
            if instance.parent_id is not None:
                    if instance.parent_id.is_notification:
                        context_type = instance.comment_type
                        comment_type_id = instance.comment_type_id
                        url = None
                        if context_type == 'Review':
                            qry_review = Review.objects.filter(id=comment_type_id)
                            if qry_review.exists():
                                url = 'http://{}/{}/{}/'.format(domain, qry_review[0].brands.all()[0].slug, qry_review[0].slug)
                        elif context_type == 'Brand':
                            qry_review_brand = ReviewBrand.objects.filter(id=comment_type_id)
                            if qry_review_brand.exists():
                                url = 'http://{}/brand/{}/'.format(domain, qry_review_brand[0].slug)
                        elif context_type == 'Category':
                            qry_review_category = ReviewCategory.objects.filter(id=comment_type_id)
                            if qry_review_category.exists():
                                url = 'http://{}/category/{}/'.format(domain, qry_review_category[0].slug)
                        elif context_type == 'Custom_Landing':
                            qry_page = Pages.objects.filter(id=comment_type_id)
                            if qry_page.exists():
                                url = 'http://{}/{}/'.format(domain, qry_page[0].slug)

                        # Use below function for send comment id.
                        # send_reply_mail(instance, url)

                        unsubscribe_url = '{}/customadmin/unsubscribe/{}'.format(domain, instance.parent_id.id)
                        send_reply_mail(instance, unsubscribe_url)

        return instance


class CommentsChangeForm(forms.ModelForm):
    """Custom Comments"""
    class Meta:
        model = Comments
        fields = ['name', 'email', 'description', 'is_approved']
        exclude = ('create_at', 'update_at')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        cleaned_data = super(CommentsChangeForm, self).clean()
        name = cleaned_data.get("name")
        # email = cleaned_data.get("email")
        description = cleaned_data.get("description")

        # if not name:
        #     raise forms.ValidationError("Please enter name.")

        if not description:
            raise forms.ValidationError("Please enter description.")

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()
        return instance

ebr-randy-develop/core/templates/core/adminuser/password_change_form.html
{% extends 'core/change_form.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}
    Change Password
{% endblock%}


{% block page_header %}
    Change Password
{% endblock%}


{% block current_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'core:index' %}">{% trans 'Home' %}</a>
</li>
<li class="breadcrumb-item">
    <a href="">{{ opts.verbose_name_plural|capfirst }}</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url opts|admin_urlname:'update' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
</li>
<li class="breadcrumb-item">
    {% trans 'Change Password' %}
</li>
{% endblock %}


{% block formset_errors %}
    {% include "core/partials/form_errors.html" with form=form %}
{% endblock%}


{% block page_content %}
    <form id="password-form" action="" method="post" enctype="multipart/form-data" autocomplete="off">

        {% include "core/partials/form_hidden_fields.html" %}

        <div class="ibox float-e-margins">

            {% include "core/partials/ibox_title.html" with ibox_title="Change Password" only %}

            <div class="ibox-content">

                <p>{% blocktrans with username=object %}Enter a new password for the user <strong>{{ username }}</strong>.{% endblocktrans %}</p>

                <div class="row">
                    <div class="col-sm-6">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="col-sm-6">
                        {{ form.password2|as_crispy_field }}
                    </div>
                </div>

            </div>
            <!-- /ibox-content -->

        </div>
        <!-- /ibox -->

        <div class="modal-footer">
            <a href="javascript:history.back()" class="btn btn-white"><i class="fa fa-times"></i> Cancel</a>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Save</button>
        </div>

    </form>

{% endblock %}


{% block js %}
{{ block.super }}

<script>
    $(function() {
        // userroles.users.details();
    });
</script>
{% endblock %}

ebr-randy-develop/core/templates/core/adminuser/user_details.html
{% extends 'core/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block page_content %}
    {% csrf_token %}

    

    {% include "core/includes/list_header_card.html" with title="User Details" subtitle="Create a new user and assign with individual or group permissions." show_button=True %}

    <div class="ibox float-e-margins">
     

        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="{{ opts.model_name }}-table">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Mobile No</th>
                            <th>Status</th>
                            <th>Customer id</th>
                            <th>Created at</th>
                            <th>Profile picture</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Mobile No</th>
                            <th>Status</th>
                            <th>Customer id</th>
                            <th>Created at</th>
                            <th>Profile picture</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for o in user_list %}
                        <tr>
                            <td>{{ o.first_name }}</td>
                            <td>{{ o.last_name }}</td>
                            <td>{{ o.email }}</td>
                            <td>{{ o.phone }}</td>
                            <td>{% show_check o.is_active %}
                            </td>
                            <td>{{ o.customer_id }}</td>
                            <td>{{ o.created_at }}</td>
                            {% if o.profile_picture == "sample.jpg" %}
                            <td><img src="{% static 'img/django-logo-negative.svg' %}" width="50px;" height="50px;"></td>
                            {% elif o.profile_picture %}
                            <td><img src="{{ o.profile_picture.url }}" width="50px;" height="50px;"></td>
                            {% else %}
                            <td><img src="{% static 'img/django-logo-negative.svg' %}" width="50px;" height="50px;"></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

ebr-randy-develop/core/templates/core/adminuser/user_list.html
{% extends 'core/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block page_content %}
    {% csrf_token %}

    {% include "core/includes/list_header_card.html" with title="Create a new user" subtitle="Create a new user and assign with individual or group permissions." show_button=True %}

    <div class="ibox float-e-margins">
        {% comment %} <div class="ibox-title">
            <div class="ibox-tools">
                {% if perms.users.add_user %}
                <a href="{% url opts|admin_urlname:'create' %}" class="btn btn-primary btn-lg"><i class="fa fa-plus"></i> Add {{ opts.verbose_name|capfirst }}</a>
                {% endif %}
            </div>
        </div> {% endcomment %}


        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="{{ opts.model_name }}-table">
                    <thead>
                        <tr>
                            <th>Company Name</th>
                            <th>Orgnization Number</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Company Name</th>
                            <th>Orgnization Number</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for o in object_list %}
                        <tr>
                            <td>{{ o.company_name }}</td>
                            <td>{{ o.orgnization_number }}</td>
                            <td>{{ o.first_name }}</td>
                            <td>{{ o.last_name }}</td>
                            <td>{{ o.email }}</td>
                            <td>{{ o.phone }}</td>
                            <td class="installer">
                            {% if o.status == 'PENDING' %}
                                <a href="#" class="btn btn-danger btn-xs" onclick="decline_user('{{ o.pk }}')">Decline</a>    
                                <a href="#" class="btn btn-success btn-xs" onclick="approve_user('{{ o.pk }}')">Approve</a>
                            {% else %}
                                {{o.status|lower}}
                            {% endif %}
                            </td>
                            
                            <td class="row-actions">
                                {% include "core/partials/list_row_actions.html" %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
<script src="{% static 'core/js/userroles.js' %}"></script>

<script>
    var pagination_url = "{% url opts|admin_urlname:'list-ajax' %}";
    $(function () {
        userroles.users.index();    
    });
</script>
<script>
    function approve_user(user_id){
        $.ajax({
            url: "{% url 'core:approve-user' %}",
            data: {
            'user_id': user_id
            },
            dataType: 'json',
            success: function (data) { 
                setTimeout(location.reload(true),200)
            }
        });
    }
    function decline_user(user_id){
        $.ajax({
            url: "{% url 'core:decline-user' %}",
            data: {
            'user_id': user_id
            },
            dataType: 'json',
            success: function (data) { 
                setTimeout(location.reload(true),200)
            }
        });
    }
</script>
{% endblock %}