ebr-randy-develop/ebr_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from frontend.sitemaps import StaticViewSitemap, ReviewCategorySitemap, ReviewBrandSitemap, ReviewSitemap, PagesSitemap

sitemaps = {
    'static': StaticViewSitemap, 'review_category': ReviewCategorySitemap,
    'review_brand': ReviewBrandSitemap, 'review': ReviewSitemap,
    'pages': PagesSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customadmin/', include("core.urls")),
    path('', include("frontend.urls")),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps, 'template_name': 'frontend/custom_sitemap.html'}),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),


    #change


    path('customlogin/',include('customloginapp.urls'))


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'frontend.views.error_404_view'

ebr-randy-develop/frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"


urlpatterns = [
	# Extra API for EBR.
	path('dashboard-integration/shops-nearby/', views.shops_nearby, name='shops_nearby'),
	path('dashboard-integration/shops-osm/', views.shops_osm, name='shops_osm'),
	path('ar/brands/', views.brand_json, name='brand_json'),
	path('wp-json/dashboard/brands/', views.dashboard_brands, name='dashboard_brands'),
	path('visitor_history/', views.visitor_history, name='visitor_history'),

	path('', views.index, name='dashboard'),
	path('category/', views.category, name='category'),
	path('category/<str:cat_slug>/', views.category_detail, name='category_detail'),
	path('search_filter/', views.search_filter, name='search-filter'),
	path('price-range/', views.price_range_filter, name='price-range-filter'),
	path('more-filter/', views.more_filter, name='more-filter'),
 
	path('display-comments/', views.display_comments, name='display-comments'),
	path('display-sub-comments/', views.display_sub_comments, name='display-sub-comments'),
 
	path('search/', views.category_filter, name='search-reviews'),

	path('category-count-ajax/', views.category_count_ajax, name='category-count-ajax' ),

	path('brand/', views.brand, name='brand'),
	path('brand/<str:brand_slug>/', views.brand_details, name='brand_details'),
	path('review_seo', views.review_seo, name='review_seo'),
 
 	path('send-message/', views.send_message, name='send_message'),
 	# path('send-message/<str:page_slug>/', views.send_message, name='send_message'),

	path('<str:brand_slug>/<str:slug>/', views.review_detail, name='review-detail'),
	path('add-new-comment/', views.add_new_comment, name='add-new-comment'),
	# path('add-new-comment/<str:brand_slug>/<str:slug>/', views.add_new_comment, name='add-new-comment'),
	path('compare/', views.compare, name='compare'),
 
 	# path('contact/', views.contact_us, name='contact'),
	# path('upvote-to-comment/', views.upvote_to_comment, name='upvote-to-comment'),

	path('highlights/update_vote', views.highlights_update_vote, name='highlights_update_vote'),
	path('highlights/get', views.get_review_highlights, name='get_review_highlights'),

	# path('<str:brand>/<str:slug>/', views.review_page, name='review'),
	path('<str:page_slug>/', views.page_view, name='page_view'),
	path('add_datas/<int:pk>', views.add_fields, name='add_datas'),
]

ebr-randy-develop/core/models/comment.py
from django.db import models
from ckeditor.fields import RichTextField
from core.models import User

CommnetType = (
    ("Review", 'Review'),
    ("Brand", 'Brand'),
    ("Category", 'Category'),
    ("Custom_Landing", 'Custom Landing'),
)


class Comments(models.Model):
    ip = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    description = RichTextField()
    comment_type = models.CharField(max_length=255, choices=CommnetType, default='Review')
    comment_type_id = models.IntegerField()
    is_approved = models.BooleanField(default=False)
    parent_id = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='child_comment')
    is_spam = models.BooleanField(default=False)
    is_notification = models.BooleanField(default=False)
    old_id = models.IntegerField(default=0)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.name:
            return str(self.name)
        else:
            return 'anonymous'

    class Meta:
        db_table = "comments"
        verbose_name = "comment"
        verbose_name_plural = "comments"
        indexes = [
            models.Index(fields=['id']),
            models.Index(fields=['ip', 'is_approved']),
        ]


class UpVote(models.Model):
    comment_id = models.ForeignKey(Comments, on_delete=models.CASCADE)
    ip = models.CharField(max_length=50, null=False, blank=False)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "upvote"
        verbose_name = "upvote"
        verbose_name_plural = "upvotes"
        indexes = [
            models.Index(fields=['id']),
            models.Index(fields=['ip']),
        ]

ebr-randy-develop/core/models/contact.py
from django.db import models


class ContactUs(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    message = models.TextField()
    is_spam = models.BooleanField(default=False)
    
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.name)
    
    class Meta:
        db_table = "contact_us"
        verbose_name = "contact_us"
        verbose_name_plural = "contact_us"

ebr-randy-develop/core/models/pages.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from . import User, Review, ReviewCategory, ReviewBrand
from django.db.models.signals import pre_save, post_save
from core.utils import pages_slugify
from .model_changes import BikeClass

PUBLISH_STATUS = (
	('Published', 'Published'),
	('Draft', 'Draft'),
)

BOOL_CHOICES = ((True, 'Basic Search Filter'), (False, 'Advanced Search Filter'))


class Pages(models.Model):
	page_title = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, unique=True)
	meta_title = models.CharField(max_length=255)
	description = RichTextUploadingField()
	is_filter = models.BooleanField(default=False)
	search_text = models.CharField(max_length=255, null=True, blank=True)
	status = models.CharField(max_length=50, choices=PUBLISH_STATUS, default='Draft')

	filter_type = models.BooleanField(choices=BOOL_CHOICES, default='True')

	model_name = models.CharField(max_length=200, blank=True, null=True)
	trim = models.CharField(max_length=200, blank=True, null=True)
	min_year = models.CharField(max_length=20, blank=True, null=True)
	max_year = models.CharField(max_length=20, blank=True, null=True)
	brands = models.ManyToManyField(ReviewBrand, db_index=True, related_name='pages_brand', blank=True)
	categories = models.ManyToManyField(ReviewCategory, db_index=True, related_name='pages_category', blank=True)
	min_price = models.IntegerField(default=0, blank=True, null=True)
	max_price = models.IntegerField(default=0, blank=True, null=True)
	suspension = models.CharField(max_length=255, blank=True, null=True)
	motor_type = models.CharField(max_length=255, blank=True, null=True)
	min_battery_capacity = models.IntegerField(default=0, blank=True, null=True)
	max_battery_capacity = models.IntegerField(default=0, blank=True, null=True)
	min_weight = models.IntegerField(default=0, blank=True, null=True)
	max_weight = models.IntegerField(default=0, blank=True, null=True)
	bike_class = models.CharField(max_length=255, null=True, blank=True)
	demo_page_bike_class = models.ManyToManyField(BikeClass, db_index=True, related_name='demo_page_bike_class_changes', blank=True)
	accessories = models.CharField(max_length=255, null=True, blank=True)
	keyword = models.CharField(max_length=255, null=True, blank=True)

	create_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return str(self.page_title)

	def get_absolute_url(self):
		return f"/{self.slug}/"

	class Meta:
		db_table = "pages"
		verbose_name = "Page"
		verbose_name_plural = "Pages"
		indexes = [
			models.Index(fields=['id']),
			models.Index(fields=['slug']),
		]


# Here we are use signal for create slug.
def review_category_pre_save(sender, instance, *args, **kwargs):
	"""
		Pre save signal use for review category slug generate.
	"""
	# print('pre_save')
	if instance.slug is None or instance.slug == '':
		pages_slugify(instance, save=False)
	else:
		pages_slugify(instance, save=False, new_slug=instance.slug)
	if instance.meta_title is None or instance.meta_title == '':
		try:
			instance.meta_title = instance.page_title.title() + ' | ElectricBikeReview.com'
			instance.save()
		except:
			pass


pre_save.connect(review_category_pre_save, sender=Pages)


def review_category_post_save(sender, instance, created, *args, **kwargs):
	"""
		Post save signal use for review category slug generate.
	"""
	# print('post_save')
	if created:
		if instance.slug is None:
			pages_slugify(instance, save=False)
		else:
			pages_slugify(instance, save=False, new_slug=instance.slug)
	if instance.meta_title is None or instance.meta_title == '':
		try:
			instance.meta_title = instance.page_title.title() + ' | ElectricBikeReview.com'
			instance.save()
		except:
			pass


post_save.connect(review_category_post_save, sender=Pages)

ebr-randy-develop/core/forms/comments.py
# -*- coding: utf-8 -*-
from django import forms
from core.models import Comments, Review, ReviewBrand, ReviewCategory, Pages
from core.utils import send_reply_mail


# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------
class CommentsCreationForm(forms.ModelForm):
    """Custom Comments"""
    class Meta:
        model = Comments
        fields = ['name', 'email', 'ip', 'description', 'is_approved']
        # exclude = ('create_at', 'update_at')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    # def clean(self):
    #     cleaned_data = super(CommentsCreationForm, self).clean()
        # parent_id = cleaned_data.get('parent_id')
        # if parent_id is None:
        #     raise forms.ValidationError("Please parent comment not found.")

    def save(self, commit=True):
        instance = super().save(commit=False)
        domain = 'http://54.213.76.238'
        if commit:
            instance.save()
            if instance.parent_id is not None:
                    if instance.parent_id.is_notification:
                        context_type = instance.comment_type
                        comment_type_id = instance.comment_type_id
                        url = None
                        if context_type == 'Review':
                            qry_review = Review.objects.filter(id=comment_type_id)
                            if qry_review.exists():
                                url = 'http://{}/{}/{}/'.format(domain, qry_review[0].brands.all()[0].slug, qry_review[0].slug)
                        elif context_type == 'Brand':
                            qry_review_brand = ReviewBrand.objects.filter(id=comment_type_id)
                            if qry_review_brand.exists():
                                url = 'http://{}/brand/{}/'.format(domain, qry_review_brand[0].slug)
                        elif context_type == 'Category':
                            qry_review_category = ReviewCategory.objects.filter(id=comment_type_id)
                            if qry_review_category.exists():
                                url = 'http://{}/category/{}/'.format(domain, qry_review_category[0].slug)
                        elif context_type == 'Custom_Landing':
                            qry_page = Pages.objects.filter(id=comment_type_id)
                            if qry_page.exists():
                                url = 'http://{}/{}/'.format(domain, qry_page[0].slug)

                        # Use below function for send comment id.
                        # send_reply_mail(instance, url)

                        unsubscribe_url = '{}/customadmin/unsubscribe/{}'.format(domain, instance.parent_id.id)
                        send_reply_mail(instance, unsubscribe_url)

        return instance


class CommentsChangeForm(forms.ModelForm):
    """Custom Comments"""
    class Meta:
        model = Comments
        fields = ['name', 'email', 'description', 'is_approved']
        exclude = ('create_at', 'update_at')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        cleaned_data = super(CommentsChangeForm, self).clean()
        name = cleaned_data.get("name")
        # email = cleaned_data.get("email")
        description = cleaned_data.get("description")

        # if not name:
        #     raise forms.ValidationError("Please enter name.")

        if not description:
            raise forms.ValidationError("Please enter description.")

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()
        return instance

ebr-randy-develop/core/forms/menus.py
# -*- coding: utf-8 -*-
from django import forms
from core.models import Menus
import validators


# -----------------------------------------------------------------------------
# Menus
# -----------------------------------------------------------------------------
class MenusCreationForm(forms.ModelForm):
    """Custom Menus"""
    link = forms.CharField(required=False)
    parent_menu = forms.ModelChoiceField(queryset=Menus.objects.filter(parent_menu=None), required=False)

    class Meta:
        model = Menus
        exclude = ('create_by', 'create_at', 'update_at')
        labels = {
            'menu_location': 'Menu Location',
            'parent_menu': 'Parent Menu',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        cleaned_data = super(MenusCreationForm, self).clean()
        name = cleaned_data.get("name")
        link = cleaned_data.get("link")
        order = cleaned_data.get("order")
        parent_menu = cleaned_data.get("parent_menu")
        menu_location = cleaned_data.get("menu_location")

        if not name:
            raise forms.ValidationError("Please enter Title.")

        if link:
            valid = validators.url(link)
            if valid is not True:
                raise forms.ValidationError("Please enter valid link.")
        if order:
            qry = Menus.objects.filter(order=order, parent_menu=parent_menu, menu_location=menu_location)
            if qry.exists():
                raise forms.ValidationError("Please select other order for same menu.")

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()
        return instance


class MenusChangeForm(forms.ModelForm):
    """Custom form to change Menus"""
    link = forms.CharField(required=False)

    class Meta:
        model = Menus
        exclude = ('create_by', 'create_at', 'update_at')
        labels = {
            'menu_location': 'Menu Location',
            'parent_menu': 'Parent Menu',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields[field].queryset = Menus.objects.filter(parent_menu=None).exclude(id=self.instance.id)

    def clean(self):
        cleaned_data = super(MenusChangeForm, self).clean()
        name = cleaned_data.get("name")
        link = cleaned_data.get("link")
        order = cleaned_data.get("order")
        parent_menu = cleaned_data.get("parent_menu")
        menu_location = cleaned_data.get("menu_location")

        if not name:
            raise forms.ValidationError("Please enter Title.")

        if link:
            valid = validators.url(link)
            if valid is not True:
                raise forms.ValidationError("Please enter valid link.")

        if order:
            qry = Menus.objects.filter(order=order, parent_menu=parent_menu, menu_location=menu_location).exclude(id=self.instance.id)
            print(qry)

            if qry.exists():
                raise forms.ValidationError("Please select other order for same menu.")

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()
        return instance

ebr-randy-develop/core/templates/core/review_brand/review_brand_details.html
{% extends 'core/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}

{% block current_breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'core:index' %}">{% trans 'Home' %}</a>
    </li>

    <li class="breadcrumb-item">
        <a href="{% url 'core:channel-list' %}">{% trans 'Channels' %}</a>
    </li>

    <li class="breadcrumb-item active">
        {{ channel.name }}
    </li>
{% endblock%}


{% block page_content %}
    {% csrf_token %}

    <header class="list-header card mb-4">
        <div class="card-body clearfix">
            <div class="float-left">
                <h5 class="card-title">Channel Details</h5>
                <p class="card-subtitle text-muted">Below is the brief details about the Channel.</p>
            </div>

            <div class="float-right lead">
                <a href="{% url 'core:channel-update' channel.id %}" class="btn btn-primary btn-lg"><i class="fa fa-plus"></i> Add New Song</a>
            </div>
        </div>
    </header>

    <div class="ibox float-e-margins">

        <div class="ibox-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox-content p-xl less-space-content">
                        <div class="row">
                            <div class="col-sm-12 text-center">

                                <div class="card-box-custom song-card-box-custom">
                                    <div class="card-box-custom-row">
                                        <div class="image-thumb">
                                            <img src="{{ channel.image }}" alt="Channel Image" class="img-responsive"/>
                                        </div>

                                        <div class="content-div-div">
                                            <div class="content-div-row">
                                                <div class="text-title-box">
                                                    <h5>Name</h5>
                                                    <h3>{{ channel.name }}</h3>
                                                </div>

                                                <div class="inner-row-details-div">
                                                    {%if channel.curator.name%}
                                                    <div class="box-card-inner-grid">
                                                        <h5>Curator</h5><h4>{{ channel.curator.name }}</h4>
                                                    </div>
                                                    {%endif%}
                                                    <div class="box-card-inner-grid">
                                                        <h5>Category</h5><h4>{{ channel.category.title }}</h4>
                                                    </div>
                                                    <div class="box-card-inner-grid">
                                                        <h5>Likes</h5><h4>{{ channel.channellike_channel.count }}</h4>
                                                    </div>
                                                    <div class="box-card-inner-grid">
                                                        <h5>Followers</h5><h4>{{ channel.channelfollow_channel.count }}</h4>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br/>
                        <hr class="w-100">
                        <div class="row">
                            <div class="col-sm-12 text-left">
                                <div class="title-common-all">
                                    <h3>Description</h3>
                                    <h5>{{ channel.description|striptags }}</h5>
                                </div>
                            </div>
                        </div>
                        <hr class="w-100">
                        <div class="row">
                            <div class="col-sm-12 text-left">
                                <div class="title-common-all">
                                    <h3>Channel Songs</h3>
                                </div>
                                <table class="table table-striped table-bordered table-hover" id="paginate-table">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>File</th>
                                        <th>Likes</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>File</th>
                                        <th>Likes</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for o in song_data %}
                                        {% for song in o.song.all %}
                                            <tr>
                                                <td><img src="{{ song.image }}" alt="Channel Image" width="50px;" height="50px;"/></td>
                                                <td><a href="{% url 'core:song-detail' song.pk %}">{{ song.name }}</a></td>
                                                <td class="audio-box">
                                                    <audio controls>
                                                        <source src="{{ song.audio_file }}" type="audio/mpeg">
                                                        Your browser does not support the audio element.
                                                    </audio>
                                                </td>
                                                <td>{{ song.songlike_song.count }}</td>
                                            </tr>
                                        {% endfor %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $('#paginate-table').DataTable({
                pageLength: 25,
                responsive: true,
                order: [[ 1, "asc" ]],
                columnDefs: [{
                    orderable: false,
                    targets: [ 0, -1, -2 ]
                },]
            });
        });
    </script>
{% endblock %}

ebr-randy-develop/core/templates/core/review_brand/review_brand_form.html
{% extends 'core/change_form.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block page_content %}
    <form id="{{ opts.model_name }}-form" action="" method="post" enctype="multipart/form-data" autocomplete="off">
        {{ form.media }}
        {% include "core/partials/form_hidden_fields.html" %}

        <div class="ibox float-e-margins">
            {% include "core/partials/ibox_title.html" with ibox_title="Review Brand Details" icon_class="fas fa-info-circle" only %}
            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.name|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.slug|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.meta_title|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.parent_brand|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.short_description|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2">
                        {{ form.featured_review|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-2 checkbox-space">
                        {{ form.brand_image_full|as_crispy_field }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 mt-2 text-center">
                        <div id="image-holder">
                            {% if form.brand_image_full.value %}
                                <p>Image Preview</p>
                                <a href="{{ form.brand_image_full.value.url }}" target="_blank"><img id="prev_image" src="{{ form.brand_image_full.value.url }}" style="width: 300px; height: 200px; object-fit: contain;"/></a>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 mt-2 checkbox-space">
                        {{ form.brand_image_grayscale_full|as_crispy_field }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 mt-2 text-center">
                        <div id="image-holder">
                            {% if form.brand_image_grayscale_full.value %}
                                <p>Image Preview</p>
                                <a href="{{ form.brand_image_grayscale_full.value.url }}" target="_blank"><img id="prev_image" src="{{ form.brand_image_grayscale_full.value.url }}" style="width: 300px; height: 200px; object-fit: contain;"/></a>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 mt-2 checkbox-space">
                        {{ form.brand_image_darkmode_full|as_crispy_field }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 mt-2 text-center">
                        <div id="image-holder">
                            {% if form.brand_image_darkmode_full.value %}
                                <p>Image Preview</p>
                                <a href="{{ form.brand_image_darkmode_full.value.url }}" target="_blank"><img id="prev_image" src="{{ form.brand_image_darkmode_full.value.url }}" style="width: 300px; height: 200px; object-fit: contain;"/></a>
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
            <!-- /ibox-content -->
        </div>
        <!-- /ibox -->
        {% include "core/partials/form_footer.html" %}
    </form>

{% endblock %}


{% block js %}
    {{ block.super }}
    <script>
        function titleCase(str) {
          str.toLowerCase();
          var strAr = str.split(" ");
          for(var i=0;i<strAr.length;i++)
          {
             strAr[i] = strAr[i].charAt(0).toUpperCase() + strAr[i].substring(1).toLowerCase();
          }
          str = strAr.join(" ");
          return str;
        }

        $('#id_name').on('keyup', function(){
            static_meta = ' | ElectricBikeReview.com';
            name = $(this).val();
            link = $('#id_meta_title').val(titleCase(name)+static_meta);
        });

        $('#id_meta_title').on('dblclick', function(){
            $('#id_meta_title').attr('readonly', false)
        });

    </script>
{% endblock %}